#!/bin/bash

if [ -z "$DFM_SUBCOMMAND" ]; then
    echo "Subcommand $0 should be called using 'dfm' command."
    exit 1
fi

cd "$DFM_DOTFILES" || exit 1

if [ -z "$(git status -s)" ]; then
    exit 0
fi

username=$USER
branch_time=$(date '+%Y%m%d%H%M%S')
commit_time=$(date '+%Y/%m/%d %H:%M:%S')
backup_branch="backup_${username}_${branch_time}"
original_branch=$(git branch --show-current)

git checkout -b "$backup_branch"
git add -A
git commit -m "[Backup] By ${username} on ${commit_time}"
git push -u origin "$backup_branch"
git checkout "$original_branch"
git diff .."$backup_branch" | git apply

cd - || exit 1