#!/bin/bash

package="$1"

# Validate if package is defined
if ! output=$(yq ".packages.$package" < "$DFM_YAML") || [ -z "$output" ] || [ "$output" = "null" ]; then
    echo "Package '$package' is not defined in '$DFM_YAML'."
    exit 1
fi

# Check for empty deps or missing entry
if ! output=$(yq ".packages.$package.deps" < "$DFM_YAML") || [ -z "$output" ] || [ "$output" = "null" ]; then
    exit 0
fi

# Get deps and output
mapfile -t deps < <(yq ".packages.$package.deps" < "$DFM_YAML" | sed 's/^- //')

for dep in "${deps[@]}"; do
    echo "$dep"
done

exit 0