#!/bin/bash

printf "Do you want to install dfm? (y/n): "
read -r answer

if [ "$answer" != "y" ]; then
    echo "Installation aborted by the user."
    exit 0
fi

# Install pre requisites
os_name="$(uname -s)"

case "$os_name" in
    Linux)
        if ! command -v yq &>/dev/null; then
            if ! command -v wget &>/dev/null; then
                echo "Installing wget..."
                
                if ! (sudo apt-get update && sudo apt-get install -y wget); then
                    echo "Error installing wget. Aborting."
                    exit 1
                fi
            fi

            echo "Installing yq..."
            
            if ! (sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq && sudo chmod +x /usr/local/bin/yq); then
                echo "Error installing yq. Aborting."
                exit 1
            fi
        fi
        ;;
    Darwin)
        if ! command -v yq &>/dev/null; then
            if ! command -v brew &>/dev/null; then
                echo "Installing Homebrew..."

                if ! (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"); then
                    echo "Error installing Homebrew. Aborting."
                    exit 1
                fi
            fi

            echo "Installing yq..."
            
            if ! (brew install yq); then
                echo "Error installing yq. Aborting."
                exit 1
            fi
        fi
        ;;
    *)
        echo "Unsupported OS: $os_name"
        exit 1
        ;;
esac

# Clone dfm
dfm_dir="$HOME/.dfm"

echo "Installing dfm in '$dfm_dir'..."

if [ -d "$dfm_dir" ]; then
    echo ".dfm directory already exists, aborting."
    exit 1
fi

echo "Cloning repository..."

if ! (git clone https://github.com/xilixio/df.git "$dfm_dir"); then
    echo "Failed installing dfm. Error: Could not clone the repository."
    exit 1
fi

# Add dfm/bin to PATH
shell_config_file=""
case "$SHELL" in
    */bash)
        shell_config_file="$HOME/.bashrc"
        ;;
    */zsh)
        shell_config_file="$HOME/.zshrc"
        ;;
    *)
        echo "Unsupported shell. Only bash and zsh are supported."
        exit 1
        ;;
esac

echo "Updating PATH in shell config '$shell_config_file'..."

if ! (echo "export PATH=\"\$PATH:$dfm_dir/bin/dfm\"" >> "$shell_config_file"); then
    echo "Failed installing dfm. Error: Could not update shell configuration."
    exit 1
fi

if ! (echo "export DFM_DOTFILES=\"\$HOME/.dotfiles\"" >> "$shell_config_file"); then
    echo "Failed installing dfm. Error: Could not update shell configuration."
    exit 1
fi

if ! (echo "export DFM_YAML=\"\$DFM_DOTFILES/packages.yaml\"" >> "$shell_config_file"); then
    echo "Failed installing dfm. Error: Could not update shell configuration."
    exit 1
fi

echo "Reloading shell config '$shell_config_file'..."
source "$shell_config_file"

echo ""
echo "Successfully installed dfm."