#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <package> <targetfile>"
    exit 1
fi

package="$1"
targetfile="$2"

if ! output=$(yq ".packages.$package" < "$DFM_YAML" 2>/dev/null) || [ -z "$output" ] || [ "$output" = "null" ]; then
    echo "Error: Package '$package' is not defined in '$DFM_YAML'."
    exit 1
fi

if [ ! -e "$targetfile" ]; then
    echo "Error: Target file '$targetfile' doesn't exist."
    exit 1
fi

if [ ! -L "$targetfile" ]; then
    echo "Error: Target file '$targetfile' is not a symlink."
    exit 1
fi

targetfile_realpath=$(realpath "$targetfile")
package_path=$(realpath "$DFM_DOTFILES")/packages/$package

if [ ! -d "$package_path" ]; then
    echo "Error: Package '$package' doesn't have a corresponding folder 'packages/$package'"
    exit 1
fi

if [[ "$targetfile_realpath" != "$package_path"* ]]; then
    echo "Error: Target file's real path '$targetfile_realpath' is not within the package's path '$package_path'."
    exit 1
fi

echo "Target file '$targetfile' is linked to package '$package' via real path '$targetfile_realpath'"
