#!/bin/bash

if [ -z "$DFM_SUBCOMMAND" ]; then
    echo "Subcommand $0 should be called using 'dfm' command."
    exit 1
fi

cd "$DFM_DOTFILES" || exit 1

if ! git pull --rebase --autostash; then
    echo "Error when pulling changes, aborting."
    exit 1
fi