#!/bin/bash

if [ -z "$DFM_SUBCOMMAND" ]; then
    echo "Subcommand $0 should be called using 'dfm' command."
    exit 1
fi

machine_name=$(hostname)
os=$(uname -s)
username=$USER
commit_time=$(date '+%Y/%m/%d %H:%M:%S')

cd "$DFM_DOTFILES" || exit 1

if [ -z "$(git status -s)" ]; then
    exit 0
fi

if ! git add -A; then
    echo "Error when staging changes, aborting."
    exit 1
fi

if ! git commit -m "[Push] By ${username} on ${commit_time}. Host: ${machine_name}, OS: ${os}"; then
    echo "Error when committing changes, aborting."
    exit 1
fi

if ! git push; then
    echo "Error when pushing commit, aborting."
    exit 1
fi