#!/bin/bash

machine_name=$(hostname)
os=$(uname -s)
username=$USER
unixtime=$(date +%s)
commit="${machine_name}-${os}-${username}-${unixtime}"

cd $DFM_DOTFILES

git stash 
git pull
git stash pop
git add -A
git commit -m "[push] $commit"
git push